### ISSUE TITLE
XML parse error when parsing CERN login form

### ISSUE THREAD

**Issue by nothingface0** [CMSTrackerDPG/certifier#136]
```
Traceback (most recent call last):
  File "./certifier/views.py", line 112, in certify
    dataset = retrieve_dataset(run_number)
  File "./oms/utils.py", line 41, in retrieve_dataset
    datasets = runregistry.get_datasets(filter={"run_number": {"=": run_number}})
  File "/opt/app-root/lib64/python3.8/site-packages/runregistry/runregistry.py", line 177, in get_datasets
    initial_response = _get_page(url=url,
  File "/opt/app-root/lib64/python3.8/site-packages/runregistry/runregistry.py", line 58, in _get_page
    cookies = _get_cookies(url, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/runregistry/runregistry.py", line 43, in _get_cookies
    cookies = get_sso_cookies(url, cert, verify=False)
  File "/opt/app-root/lib64/python3.8/site-packages/cernrequests/cookies.py", line 74, in get_sso_cookies
    action, form_data = _extract_login_form(authentication_response.content)
  File "/opt/app-root/lib64/python3.8/site-packages/cernrequests/cookies.py", line 38, in _extract_login_form
    tree = ElementTree.fromstring(response_content)
  File "/usr/lib64/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
  File "<string>", line None
```

**Comment by nothingface0** [comment]
After submitting the appropriate ticket, there seems to be an [ongoing outage](https://cern.service-now.com/service-portal?id=outage&n=OTG0070623) related to CERN SSO.

**Comment by nothingface0** [comment]
Service was restored (more info [here](https://github.com/CMSTrackerDPG/cernrequests/issues/2))
