### ISSUE TITLE
403 errors upon certifying specific runs

### ISSUE THREAD

**Issue by nothingface0** [CMSTrackerDPG/certifier#97]
Reporter: @gbenelli 

Certifying the 323857 run results in the following error 
```
Oops!
404 Run Found
403 Client Error: Forbidden for url: <>
```

Traceback:

```
Traceback (most recent call last):
  File "./certifier/views.py", line 78, in certify
    dataset = retrieve_dataset(run_number)
  File "./oms/utils.py", line 41, in retrieve_dataset
    datasets = runregistry.get_datasets(
  File "/opt/app-root/lib64/python3.8/site-packages/runregistry/runregistry.py", line 177, in get_datasets
    initial_response = _get_page(url=url,
  File "/opt/app-root/lib64/python3.8/site-packages/runregistry/runregistry.py", line 58, in _get_page
    cookies = _get_cookies(url, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/runregistry/runregistry.py", line 43, in _get_cookies
    cookies = get_sso_cookies(url, cert, verify=False)
  File "/opt/app-root/lib64/python3.8/site-packages/cernrequests/cookies.py", line 72, in get_sso_cookies
    authentication_response.raise_for_status()
  File "/opt/app-root/lib64/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url
```

**Comment by nothingface0** [comment]
The issue seems to emerge when calling a `cernrequests` function (`get_sso_cookies`) is called. 
To test:
- Log into the certhelper-training PaaS project
- Open the terminal and run `python`
- ```python
  import cernrequests
  url = 'https://cmsrunregistry.web.cern.ch/api/datasets_filtered_ordered'
  cert = ('/eos/path/to/usercert.pem', '/eos/path/to/userkey.pem')
  cookies = cernrequests.get_sso_cookies(url, cert, verify=False)
```

**Comment by nothingface0** [comment]
Solved by regenerating Grid credentials for the app
